"""Add vehicle legal compliance and trip vehicle relationship

Revision ID: c111d10c6526
Revises:
Create Date: 2025-10-18 13:09:25.153086

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c111d10c6526"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("vehicle_legal_compliance_ack", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_id"), "vehicles", ["id"], unique=False)
    op.create_index(
        op.f("ix_vehicles_license_plate"), "vehicles", ["license_plate"], unique=True
    )
    op.create_table(
        "ratings",
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("rater_id", sa.Integer(), nullable=False),
        sa.Column("rated_user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rated_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rater_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ratings_id"), "ratings", ["id"], unique=False)
    op.add_column("trips", sa.Column("vehicle_id", sa.Integer(), nullable=False))
    op.add_column(
        "trips", sa.Column("trip_legal_compliance_ack", sa.Boolean(), nullable=False)
    )
    op.create_foreign_key(None, "trips", "vehicles", ["vehicle_id"], ["id"])
    op.add_column("users", sa.Column("name", sa.String(length=100), nullable=False))
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("identification", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("identification_type", sa.String(length=50), nullable=True)
    )
    op.add_column("users", sa.Column("phone_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("profile_short_bio", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("status", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("trip_preferences", sa.JSON(), nullable=True))
    op.add_column(
        "users", sa.Column("auth_provider", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("provider_user_id", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_index(
        op.f("ix_users_provider_user_id"), "users", ["provider_user_id"], unique=False
    )
    op.drop_column("users", "full_name")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_users_provider_user_id"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "provider_user_id")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "trip_preferences")
    op.drop_column("users", "status")
    op.drop_column("users", "profile_short_bio")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "phone_verified")
    op.drop_column("users", "identification_type")
    op.drop_column("users", "identification")
    op.drop_column("users", "last_name")
    op.drop_column("users", "name")
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_column("trips", "trip_legal_compliance_ack")
    op.drop_column("trips", "vehicle_id")
    op.drop_index(op.f("ix_ratings_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_vehicles_license_plate"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_id"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
