"""Add cancellation tracking fields to bookings

Revision ID: c059da7a7ad5
Revises: e8dd2932274b
Create Date: 2025-11-21 13:02:59.500758

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c059da7a7ad5"
down_revision = "e8dd2932274b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("cancelled_by", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "bookings",
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "bookings",
        sa.Column("cancellation_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "cancellation_time")
    op.drop_column("bookings", "cancellation_reason")
    op.drop_column("bookings", "cancelled_by")
    # ### end Alembic commands ###
