"""Add unique constraint for active bookings

Revision ID: e8dd2932274b
Revises: fc3b09b2e21e
Create Date: 2025-11-21 01:52:39.212540

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8dd2932274b"
down_revision = "fc3b09b2e21e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_unique_active_booking",
        "bookings",
        ["trip_id", "passenger_id"],
        unique=True,
        postgresql_where="status != 'cancelled'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_unique_active_booking",
        table_name="bookings",
        postgresql_where="status != 'cancelled'",
    )
    # ### end Alembic commands ###
